import { Inter } from "next/font/google";
import React from "react";
import "../globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="md:col-span-9 col-span-12">{children}</div>
      </body>
    </html>
  );
}
