
import Navbar from "../components/shared/navbar/Navbar";
import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return <html lang='en'>
    <body>
      <div>
        <Navbar />
        {children}
      </div>;
    </body>
  </html>;
}
