import { Inter } from "next/font/google";
import React from "react";
import AdminSidebar from "../components/shared/admin/AdminSideBar";
import "../globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full mx-auto relative">
          <div className="grid grid-cols-12 overflow-hidden ">
            <div
              className={`col-span-3 md:block hidden bg-white z-30 sticky overflow-y-auto`}
            >
              <AdminSidebar />
            </div>
            <div className="col-span-9">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
